# Generated by Django 4.2.4 on 2023-08-12 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0002_xray_result_xray_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='xray',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='xray',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
